version: "3"
services:
  books:
    container_name: app_aste_Ahmad_ELQADY
    build: .
    command: nodemon --watch . -e js app.js
    ports:
      - "3000:3000"
    volumes:
      - ./app:/var/www
    links:
      - "mongo_aste:mongohost"
  mongo_aste:
    container_name: mongo_aste
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"